export const PROJECT_GET_ERROR = 'PROJECT_GET_ERROR'
export const PROJECT_GET_ERROR_CLEAR = 'PROJECT_GET_ERROR_CLEAR'
export const PROJECT_GET_SUCCESS = 'PROJECT_GET_SUCCESS'
export const PROJECT_GET_SUCCESS_CLEAR = 'PROJECT_GET_SUCCESS_CLEAR'