export const TASK_GET_ERROR = 'TASK_GET_ERROR'
export const TASK_GET_ERROR_CLEAR = 'TASK_GET_ERROR_CLEAR'
export const TASK_GET_SUCCESS = 'TASK_GET_SUCCESS'
export const TASK_GET_SUCCESS_CLEAR = 'TASK_GET_SUCCESS_CLEAR'